feat: enhance tokens feature control and add error handling
HathorNetwork/hathor-explorer pull request #190
Opened 2022-04-28 20:50 UTC by lucas3003

### Acceptance Criteria

This PR intends to:

1. Add a feature flag to indicate the feature is under maintenance mode.
2. Add a feature flag to turn on/off the navigation bar.
3. Enhance the error handling. New message is presented if status code is different than 200. 

###  Diagram

This diagram assumes that Token feature flag is turned on.
![TokensAPI-ErrorHandling drawio](https://user-images.githubusercontent.com/3287486/165843256-502b20c0-ffef-40e3-9068-66bca70913d4.png)

2022-05-02 14:12 UTC, r4mmer requested changes

2022-05-02 14:12 UTC, r4mmer commented on src/components/token/Tokens.js
> +                    this.state.maintenanceMode ?
This ternary inside a ternary is a bit confusing, why not have a separate function to render this part and we can do this conditional rendering with 2 `if`s?

2022-05-02 22:29 UTC, r4mmer submitted a review, later dismissed

2022-05-03 00:25 UTC, pedroferreira1 requested changes

2022-05-03 00:25 UTC, pedroferreira1 commented on src/components/ConditionalNavigation.js
> +export default ConditionalNavigation;
We should add the component prop types as a documentation.

2022-05-03 00:25 UTC, pedroferreira1 commented on src/components/error/ErrorMessageWithIcon.js
> +export default ErrorMessageWithIcon;
We should add the component prop types as a documentation.

2022-05-03 00:25 UTC, pedroferreira1 commented on src/components/Navigation.js
> +              <ConditionalNavigation to="/tokens" label="Tokens" featureToggle={`explorer-tokens-${REACT_APP_NETWORK}.rollout`} />
Should we have in the constants file 

`export UNLEASH_BASE_FEATURE_FLAG = explorer-tokens-${REACT_APP_NETWORK}`

Then we can use this everywhere in the code with `UNLEASH_BASE_FEATURE_FLAG.rollout` or `UNLEASH_BASE_FEATURE_FLAG.maintenance`? What do you think?

2022-05-03 00:25 UTC, pedroferreira1 commented on src/components/token/Tokens.js
> +         * error: Indicates if and unexpected error happened when calling the explorer-service
Typo: and -> an

2022-05-03 00:25 UTC, pedroferreira1 commented on src/components/token/Tokens.js
> +         * maintenanceMode: Indicates if explorer-service or its downstream services are expecting
are expecting ... ?

2022-05-03 00:25 UTC, pedroferreira1 commented on src/components/token/Tokens.js
> +            maintenanceMode: this.props.maintenanceMode
We should add this to proptypes as well

2022-05-03 12:16 UTC, pedroferreira1 approved these changes

2022-05-03 12:16 UTC, pedroferreira1 commented on src/components/ConditionalNavigation.js
> +    label: PropTypes.string.isRequired
You have `to` and `featureToggle` here as well, right?

2022-05-03 13:25 UTC, pedroferreira1 approved these changes

2022-05-03 16:14 UTC, r4mmer approved these changes

2022-05-03 17:46 UTC, merged