Fix: revamp can mint tokens
HathorNetwork/hathor-explorer pull request #363
Opened 2024-12-19 18:29 UTC by lacerdamurilo

### Acceptance Criteria
- Fixing canMint validation in TokenDetail
  - Now the "CAN MINT NEW TOKENS" field receives false if the token object's mint is an empty array, and true otherwise.

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

[Vídeo 12-19 às 15.24 (1).webm](https://github.com/user-attachments/assets/13d2e8c5-d7ca-492e-b898-14aead069b3f)

2024-12-20 14:50 UTC, tuliomir requested changes

2024-12-20 14:50 UTC, tuliomir commented on src/newUi.scss
issue: I believe these changes are not part of this PR.

2024-12-27 19:27 UTC, lacerdamurilo commented on src/newUi.scss
Indeed, these changes belong to another PR. Thank you for pointing that out! I have removed them and am now awaiting your review!

2024-12-30 11:48 UTC, tuliomir approved these changes

2025-01-02 16:55 UTC, r4mmer approved these changes

2025-01-06 18:34 UTC, merged